### ISSUE TITLE
Prevent html tags hyphenation

### ISSUE THREAD

**Issue by okansoy** [sergeysolovev/hyphenated#28]
I'm using html in the text I want to hyphenate :
``` 
  const text = 'bonjour monsieur <span>comment allez vous ?</span>';
  return(
    <Hyphenated language={fr}>
      {text}
    </Hyphenated>
  )
```
In this case, it's not working properly because it's also hyphenate the html tag, and so break the html dom :
`bon&shy;jour mon&shy;sieur <s&shy;pan>&shy;com&shy;ment allez vous ?</s&shy;pan>`

Do you think it's possible to prevent this ?

**Comment by sergeysolovev** [comment]
Hello @okansoy,

I’m afraid there is no good way to accomplish this as it’s aimed to work with plain text. Please notice that there are issues related to yours in the react-hyphen repo:

https://github.com/sergeysolovev/react-hyphen/issues/26
https://github.com/sergeysolovev/react-hyphen/issues/28

You can try to use some HTML parser and hyphenate text nodes in the parsed tree, then render it back.

Maybe @steakscience (the author of the issues above) has come up with a solution and would like to share it. We’d love to hear that.

**Comment by steakscience** [comment]
@sergeysolovev @okansoy,

For me, I was making a Gatsby project, and there was a plugin that was running hyphenated *before* HTML is generated, so I could avoid this issue.

For you, it looks like you are just running hyphenated on a string which has HTML tags inside. I think using [react-hyphen](https://github.com/sergeysolovev/react-hyphen) would work.

**Comment by sergeysolovev** [comment]
@steakscience Thank you for your time!
